"""Init-new-models

Revision ID: a65230ab32a3
Revises: 0e13a27eeb33
Create Date: 2023-10-01 20:40:35.013581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65230ab32a3'
down_revision: Union[str, None] = '0e13a27eeb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters_to_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_category_id', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('service_price', sa.Float(), nullable=False),
    sa.Column('service_sale_price', sa.Float(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.currency_id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['master_info.master_id'], ),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.service_category_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('masters_m2m_services')
    op.drop_constraint('service_categories_service_id_fkey', 'service_categories', type_='foreignkey')
    op.create_foreign_key(None, 'service_categories', 'services', ['service_id'], ['service_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_categories', type_='foreignkey')
    op.create_foreign_key('service_categories_service_id_fkey', 'service_categories', 'services', ['service_id'], ['service_id'])
    op.create_table('masters_m2m_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('service_sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.currency_id'], name='masters_m2m_services_currency_id_fkey'),
    sa.ForeignKeyConstraint(['master_id'], ['master_info.master_id'], name='masters_m2m_services_master_id_fkey'),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.service_category_id'], name='masters_m2m_services_service_category_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='masters_m2m_services_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='masters_m2m_services_pkey')
    )
    op.drop_table('masters_to_services')
    # ### end Alembic commands ###
